---
title: "Save and User Experience"
author: "Hsuan-Yu Lin"
date: "May 7, 2018"
output:
  ioslides_presentation:
    widescreen: true
    logo: images\logo-large.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, python.reticulate = FALSE)
```

## Saving file

- What we have on hand:
```{python}
trial_info = {
    'setsize': 6,
    'display_duration': 500/1000.0,
    'stimuli': [
        'bent',
        'cart',
        'line',
        'birth',
        'ultra',
        'excuse'
    ],
    'probe_type': 'old',
    'serial_position': 3,
    'probe': 'line',
    'response': 1,
    'RT': 1.732
}
```

## Saving file

- I want to record it with coding

```
1: participant ID
2: display duration
3: set size (1-6)
4: probe type (old, new)
5: serial position (-1 if probe is new)
6-11: stimuli
12: probe
13: response (1 as old, 2 as new)
14: RT
```

```
1 0.5 6 old 3 bent  cart  line  birth ultra excuse line  1 1.732
```

## Saving file

- Opening file to write:
```{python}
import codecs
save_file = codecs.open('save_file.txt', 'a', encoding = 'utf-8')

save_file.write(the_string_you_want_to_save)
```

- 'a' indicates 'appending'
- 'w' as 'write'
- 'r' as 'read'

## Saving file

- Creating the [string](https://docs.python.org/2/library/string.html)

```{python}
output_string = '' # initiate 
output_string += '{}\t'.format(pID)
output_string += '{}\t'.format(trial_info['display_duration'])
output_string += '{}\t'.format(trial_info['setsize'])
output_string += '{}\t'.format(trial_info['probe_type'])
output_string += '{}\t'.format(trial_info['serial_position'])

for stimulus in trial_info['stimuli']:
  output_string += '{}\t'.format(stimulus)
  
output_string += '{}\t'.format(trial_infi['probe'])
output_string += '{}\t'.format(trial_infi['response'])
output_string += '{}\n'.format(trial_infi['RT'])
```

## Saving file

```{python}
def saveTrial(trial_info, save_file):
  output_string = '' # initiate 
  output_string += '{}\t'.format(pID)
  output_string += '{}\t'.format(trial_info['display_duration'])
  output_string += '{}\t'.format(trial_info['setsize'])
  output_string += '{}\t'.format(trial_info['probe_type'])
  output_string += '{}\t'.format(trial_info['serial_position'])
  
  for stimulus in trial_info['stimuli']:
    output_string += '{}\t'.format(stimulus)
    
  output_string += '{}\t'.format(trial_infi['probe'])
  output_string += '{}\t'.format(trial_infi['response'])
  output_string += '{}\n'.format(trial_infi['RT'])
  
  save_file.write(output_string)
```

## Saving file

- Make sure you close the file.
```{python}
save_file.close()
```
- Bad things might happen if you do not close it.

## Surprising Exercise

- The saving code is incorrect.
- If the set size is smaller than 6, the otput_string will contain less columns because the less number of stimuli.
- FIX IT

## User Experimence

- User:
    - Experimenter
    - Participant

- Experimenter
    - Escape key
    - Auto pilot
    
- Participant
    - Breaks
    - Feedback
    
## Escape key

- Remember the [globalKeys](http://www.psychopy.org/coder/globalKeys.html) event?
    - Use the Shutdown key
    - Write your own function to shut down the program.
    
```{python}
def endofExperiment(window, save_file):
    showMessage('Experiment is over, be sure to grab your cellphone', window)
    save_file.close()
    window.close()
    sys.exit()
    
psychopy.event.globalKeys(key = 'd', func = endofExperiment)
```

## Auto pilot

- Easier to test the program
- Setup a flag, whenever there is a getKeys function, replace said function to something else

```{python}
def runTrial(trial_index, trial_info, window, autopilot = False):
    ...
    if autopilot:
        response = ['o']
    else:
        response = psychopy.event.waitKeys(
            keyList = ['o', 'n']
        )
```

## Breaks

- Please give participants a break.
    - Especially when the experiment is longer than an hour.
    
- To take a break, you need to track the current trial number
```{python}
for i, condition in enumerate(condition_indexes):
    ...
```

- Check if enough trials are finished. If yes, then take a break.
```{ptyhon}
    if i % n_trials_per_break == 0:
        showMessage('Take a break')
```


## Feedbacks

- The colorwheel example.

# ANIMATION

## Saving the frames

- This is the area I had little experince in, so keep it with a grain of salt.

- Reduce the number of drawing per frame
    1. Background/foreground strategy.
    2. "Move" the animated object.
    
## Background/foreground

- [BufferImageStim](http://www.psychopy.org/api/visual/bufferimagestim.html#psychopy.visual.BufferImageStim)